In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):  # list/ dict 是序列,要一個一個取出值, 所以用for...in...
    scores = student1[i] + student2[i]
    print(scores)
    print("===================")

144
170
164
167
177


In [4]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2 # 串接

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [7]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray = student1 + student2
for total in totols:
    print(total)
    print("============")

144
170
164
167
177


In [13]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [17]:
np.random.randint(50,101,size=(50, 5)) #效能比for...in快

array([[ 95,  65,  88,  91,  56],
       [ 70,  86,  93,  62,  58],
       [ 89,  55,  87,  50,  82],
       [ 71,  85,  92,  66,  98],
       [ 82,  72,  53,  69,  56],
       [ 96, 100,  72,  90,  54],
       [ 62,  78,  97,  67,  70],
       [ 55,  75,  51,  98,  60],
       [ 75,  94,  83,  66,  77],
       [ 68,  53,  67,  57,  54],
       [ 65,  70,  59,  84,  90],
       [ 50,  79,  75,  65,  67],
       [ 76,  72, 100,  67,  84],
       [ 91,  70,  61,  91,  91],
       [ 55,  95,  93,  52,  67],
       [ 98,  68,  76,  99,  66],
       [ 70,  94,  62,  55,  85],
       [ 53,  83,  88,  87,  83],
       [ 89,  64,  73,  94,  84],
       [ 50,  71,  60,  58,  65],
       [ 81,  96,  86,  77,  56],
       [ 52,  60,  64,  67,  95],
       [ 55,  61,  54,  63,  60],
       [ 93,  63,  95,  92,  66],
       [ 56,  74,  97,  89,  86],
       [ 74,  64, 100,  51,  99],
       [ 63,  88,  99,  75,  98],
       [ 81,  67,  66,  81,  73],
       [ 62,  81,  86,  56,  89],
       [ 73,  