In [3]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):  # list/ dict 是序列,要一個一個取出值, 所以用for...in...
    scores = student1[i] + student2[i]
    print(scores)
    print("===================")

144
170
164
167
177


In [4]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2 # 串接

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [7]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray = student1 + student2
for total in totols:
    print(total)
    print("============")

144
170
164
167
177


In [13]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int64


In [19]:
abc = np.random.randint(50,101,size=(50, 5)) #效能比for...in快

array([[4350, 2601, 5040, 4590, 5467],
       [6762, 3120, 4891, 5600, 4554],
       [4150, 6111, 5734, 3640, 5292],
       [5548, 7055, 8178, 6210, 8148],
       [6016, 7905, 7200, 4212, 7300],
       [3417, 5396, 5530, 5346, 4686],
       [5550, 5159, 3172, 4896, 5162],
       [7209, 5358, 3630, 6052, 4212],
       [4560, 8645, 5734, 3300, 4293],
       [5568, 5440, 4731, 5184, 3840],
       [3672, 4800, 6384, 4717, 5146],
       [5673, 7052, 8554, 4698, 2808],
       [7448, 3990, 3960, 5500, 5880],
       [6408, 7098, 3570, 8280, 3944],
       [5229, 4347, 4992, 8910, 7056],
       [6231, 4416, 5428, 6384, 8448],
       [5704, 3190, 6237, 4352, 7440],
       [6068, 4970, 4800, 4550, 6912],
       [7308, 7221, 6880, 6960, 8091],
       [9212, 6231, 8010, 4424, 4977],
       [3774, 4160, 5369, 6144, 6365],
       [8924, 4700, 5130, 4928, 7760],
       [6396, 4539, 9603, 6402, 5795],
       [4554, 4779, 5670, 8600, 4134],
       [5246, 6880, 9506, 4743, 9900],
       [5148, 5934, 4650,